version: '3.8'

services:
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME-localstack_main}'
    image: localstack/localstack:latest
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # 外部サービス用ポート範囲
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=apigateway,lambda,s3,sqs,dynamodb,cloudformation,iam,logs,cloudwatch
      - PERSISTENCE=1
      - LAMBDA_DOCKER_NETWORK=localstack-network
      - LAMBDA_DOCKER_FLAGS=-v /var/run/docker.sock:/var/run/docker.sock --network localstack-network
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - localstack-network

networks:
  localstack-network:
    name: localstack-network
    driver: bridge
